main: com.cavetale.vote.VotePlugin
name: Vote

version: 0.1
api-version: '1.21.10'

description: Vote Plugin
author: StarTux
website: https://cavetale.com

depend: [Core, SQL, PlayerCache, Mytems, Fam, Spawn]
softdepend: [Votifier]

commands:

  vote:
    aliases: [v]
    description: Vote Command
    permission: vote.vote
    usage: |-
      /vote - General information
      /vote hi - Monthly highscore
      /vote firework - Launch fireworks

  voteadmin:
    aliases: [voteadm]
    description: Vote Command
    permission: vote.admin
    usage: |-
      /voteadm service list - 
      /voteadm service add 
      /voteadm service remove <name> - Remove service

permissions:

  vote.vote:
    description: Use /vote
    default: op

  vote.reward:
    description: Receive voting rewards
    default: false

  vote.admin:
    description: Use /votedmin and skip vote king
    default: op
